version: '3'
services:
  web:
    build: .
    container_name: flask_env
    ports:
      - '5000:5000'
    volumes:
      - './app:/app'
    tty: true
    # command: ["python", "main.py"]
